#!/bin/bash

pass=0
fail=0

read -p "Enter Student ID: " sid
read -p "Enter marks of Subject 1: " m1
read -p "Enter marks of Subject 2: " m2
read -p "Enter marks of Subject 3: " m3

total=$((m1 + m2 + m3))
percentage=$((total * 100 / 300))

if [ $percentage -ge 80 ]; then
    grade="A+"
elif [ $percentage -ge 70 ]; then
    grade="A"
elif [ $percentage -ge 60 ]; then
    grade="B"
elif [ $percentage -ge 50 ]; then
    grade="C"
else
    grade="F"
fi

if [ "$grade" == "F" ]; then
    fail=$((fail+1))
else
    pass=$((pass+1))
fi

echo "Final Summary"
echo "Student ID: $sid"
echo "Total Marks: $total"
echo "Percentage: $percentage%"
echo "Grade: $grade"
echo "Pass Students: $pass"
echo "Fail Students: $fail"
